"""Legacy constant mappings for backward compatibility with the modelscope SDK.

Every name here is re-exported from :mod:`modelscope_hub.constants`, the single
source of truth. This module defines no independent values of its own; it only
surfaces the historical names (plus a few integer / env-name aliases) that the
modelscope SDK imports.
"""

from ..constants import (  # noqa: F401
    DEFAULT_CREDENTIALS_PATH,
    DEFAULT_DATASET_REVISION,
    DEFAULT_MAX_WORKERS,
    DEFAULT_MODELSCOPE_DATA_ENDPOINT,
    DEFAULT_MODELSCOPE_DOMAIN,
    DEFAULT_MODELSCOPE_GROUP,
    DEFAULT_MODELSCOPE_INTL_DATA_ENDPOINT,
    DEFAULT_MODELSCOPE_INTL_DOMAIN,
    DEFAULT_SKILLS_DIR,
    FILE_HASH,
    MODEL_ID_SEPARATOR,
    REPO_TYPE_DATASET,
    REPO_TYPE_MODEL,
    REPO_TYPE_STUDIO,
    REPO_TYPE_SUPPORT,
    TEMPORARY_FOLDER_NAME,
    UPLOAD_ADAPTIVE_BATCH_SIZE,
    UPLOAD_ADAPTIVE_BATCHING_ENABLED,
    UPLOAD_BLOB_CONNECT_TIMEOUT,
    UPLOAD_BLOB_CONNECT_TIMEOUT_SECONDS,
    UPLOAD_BLOB_MAX_ATTEMPTS,
    UPLOAD_BLOB_MAX_RETRIES,
    UPLOAD_BLOB_PROGRESS_THRESHOLD_BYTES,
    UPLOAD_BLOB_READ_TIMEOUT,
    UPLOAD_BLOB_READ_TIMEOUT_SECONDS,
    UPLOAD_BLOB_RETRY_BACKOFF,
    UPLOAD_BLOB_RETRY_BACKOFF_BASE_SECONDS,
    UPLOAD_BLOB_RETRY_MAX_DELAY_SECONDS,
    UPLOAD_BLOB_RETRY_MAX_WAIT,
    UPLOAD_BLOB_TIMEOUT,
    UPLOAD_BLOB_TQDM_DISABLE_THRESHOLD,
    UPLOAD_BLOB_VALIDATION_BATCH_MAX_OBJECTS,
    UPLOAD_CACHE_ENABLED,
    UPLOAD_COMMIT_BATCH_MAX_OPERATIONS,
    UPLOAD_COMMIT_BATCH_SIZE,
    UPLOAD_FAILED_FILE_MAX_RETRIES,
    UPLOAD_FAILED_FILE_MAX_RETRY_ROUNDS,
    UPLOAD_HTTP_RETRY_ALLOWED_METHODS,
    UPLOAD_LFS_FORCE_THRESHOLD_BYTES,
    UPLOAD_LFS_THRESHOLD,
    UPLOAD_MAX_CONCURRENT_WORKERS,
    UPLOAD_MAX_FILE_COUNT,
    UPLOAD_MAX_FILE_COUNT_IN_DIR,
    UPLOAD_MAX_FILE_SIZE,
    UPLOAD_MAX_FILE_SIZE_BYTES,
    UPLOAD_MAX_FILES_PER_DIRECTORY,
    UPLOAD_NORMAL_FILE_SIZE_TOTAL_LIMIT,
    UPLOAD_NORMAL_FILES_TOTAL_SIZE_BYTES,
    UPLOAD_REACT_BACKOFF_MAX_EXPONENT,
    UPLOAD_REACT_ENABLED,
    UPLOAD_REACT_MAX_DELAY,
    UPLOAD_REACT_ROUND2_BASE_DELAY,
    UPLOAD_REACT_ROUND3_FILE_DELAY,
    UPLOAD_RECOVERY_BACKOFF_MAX_EXPONENT,
    UPLOAD_RECOVERY_ENABLED,
    UPLOAD_RECOVERY_MAX_DELAY_SECONDS,
    UPLOAD_RECOVERY_SERIAL_BACKOFF_BASE_SECONDS,
    UPLOAD_RECOVERY_SINGLE_FILE_DELAY_SECONDS,
    UPLOAD_RETRY_ALLOWED_METHODS,
    UPLOAD_SIZE_THRESHOLD_TO_ENFORCE_LFS,
    UPLOAD_USE_CACHE,
    UPLOAD_VALIDATE_BLOB_BATCH_SIZE,
    RepoType,
    Visibility,
    get_upload_ignore_file_pattern,
)

# Visibility integer constants matching the old SDK
ModelVisibility_PUBLIC: int = int(Visibility.PUBLIC)
ModelVisibility_PRIVATE: int = int(Visibility.PRIVATE)
ModelVisibility_INTERNAL: int = int(Visibility.INTERNAL)

# Env var name constants (old SDK imports these as string constants)
MODELSCOPE_DOMAIN: str = "MODELSCOPE_DOMAIN"
MODELSCOPE_PREFER_AI_SITE: str = "MODELSCOPE_PREFER_AI_SITE"
